{% set name = "polarify" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polarify-{{ version }}.tar.gz
  sha256: fbace7f79a740f9a8e6f6f2ed1abe3d61f7015859654233a1783e487dfcafb86

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - python >=3.9
    - polars >=0.14.24,<0.19

test:
  imports:
    - polarify
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/quantco/polarify
  summary: Simplifying conditional Polars Expressions with Python 🐍 🐻‍❄️
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
    - '0xbe7a'
